voice_files = {
    1: 'voices/52.mp3',
    2: 'voices/cadillac.mp3',
    3: 'voices/riptrappa.mp3',
    4: 'voices/vlubilas.mp3',
    5: 'voices/halloween.ogg',
    6: 'voices/venom.ogg',
    7: 'voices/wakeandbake.ogg',
    8: 'voices/Lo Siento.ogg',
    9: 'voices/tolerantnost.ogg',
    10: 'voices/soicynihao.ogg',
    11: 'voices/gimnrossii.ogg',
    12: 'voices/1hour.mp3',
    13: 'voices/retrorave.ogg',
    14: 'voices/benzomageddon.ogg',
    15: 'voices/dying2live.ogg',
    16: 'voices/pablo.ogg',
    17: 'voices/maniya.ogg',
    18: 'voices/papintank.ogg',
    19: 'voices/4x4.ogg',
    20: 'voices/hublot.ogg',
    21: 'voices/lyfe.ogg',
    22: 'voices/maksbetov1.mp3',
    23: 'voices/maksbetov2.mp3',
    24: 'voices/moybeliy.ogg',
    25: 'voices/baller.ogg',
}

music_files = {
    'guf': {
        1: 'music/guf/IceBaby.mp3',
        2: 'music/guf/Alik.mp3',
        3: 'music/guf/Amin.mp3',
        4: 'music/guf/Ballada.mp3',
        5: 'music/guf/Gangster.mp3',
        6: 'music/guf/Morgenshtern_diss.mp3',
        7: 'music/guf/Welcome.mp3',
        8: 'music/guf/If it werent for he.mp3',
        9: 'music/guf/Start of the End.mp3',
        10: 'music/guf/New.mp3',
        11: 'music/guf/A letter home.mp3',
        12: 'music/guf/Rules of home.mp3',
        13: 'music/guf/PT.mp3',
        14: 'music/guf/Round2.mp3',
        15: 'music/guf/Today-tomorrow.mp3',
        16: 'music/guf/TKDR.mp3',
        17: 'music/guf/But not today.mp3',
        18: 'music/guf/Best day.mp3',
        19: 'music/guf/Equator.mp3',
        20: 'music/guf/Guf dead.mp3',
        21: 'music/guf/The moon is setting.mp3',
        22: 'music/guf/Sponsor of your problem.mp3',
        23: 'music/guf/Sharaut.mp3',
        24: 'music/guf/Father and sons.mp3',
        25: 'music/guf/Stormy.mp3',
        26: 'music/guf/Sharaut.mp3',
    },
    'dtf': {
        1: 'music/dtf/dj trippie flameboy – B0lit _(.mp3',
        2: 'music/dtf/dj trippie flameboy – Ee Nado X).mp3',
        3: 'music/dtf/dj trippie flameboy – On the star_.mp3',
        4: 'music/dtf/dj trippie flameboy – Sexsoldier.mp3',
        5: 'music/dtf/dj trippie flameboy – Take the L.mp3',
        6: 'music/dtf/dj trippie flameboy – X_x',
        7: 'music/dtf/dj trippie flameboy – X_x 2.mp3',
        8: 'music/dtf/dj trippie flameboy – X_x 3.mp3',
        9: 'music/dtf/dj trippie flameboy – Догги.mp3',
        10: 'music/dtf/dj trippie flameboy feat. 5mewmet – Na Vse Gotova (;.mp3'
    },
    'obladaet': {
        1: 'music/obladaet/OBLADAET – 99.mp3',
        2: 'music/obladaet/OBLADAET – BARMAN.mp3',
        3: 'music/obladaet/OBLADAET – BLIND ZONE.mp3',
        4: 'music/obladaet/OBLADAET – BOO!.mp3',
        5: 'music/obladaet/OBLADAET – BRITNEY.mp3',
        6: 'music/obladaet/OBLADAET – DAVID BECKHAM.mp3',
        7: 'music/obladaet/OBLADAET – HARLEQUIN.mp3',
        8: 'music/obladaet/OBLADAET – MONSTER TRAKK.mp3',
        9: 'music/obladaet/OBLADAET – MUTANT.mp3',
        10: 'music/obladaet/OBLADAET – POSLEVKUSIE.mp3',
        11: 'music/obladaet/OBLADAET – SHINOBI.mp3',
        12: 'music/obladaet/OBLADAET – SLEEPKNOT.mp3',
        13: 'music/obladaet/OBLADAET – Большой Брат.mp3',
        14: 'music/obladaet/OBLADAET feat. FRIENDLY THUG 52 NGG – Дом с привидениями.mp3',
        15: 'music/obladaet/OBLADAET feat. LIL KRYSTALLL – MB.mp3',
        16: 'music/obladaet/OBLADAET feat. THRILL PILL – NHL MONEY.mp3',
        17: 'music/obladaet/OBLADAET feat. Unknown T – PRAYERS.mp3',
        18: 'music/obladaet/OBLADAET, JEEMBO – HELLA PLAYERS.mp3'
    }
}